### ISSUE TITLE
Does nbr.update(positions) can be contained in a jitted function?

### ISSUE THREAD

**Issue by Roy-Kid** [google/jax-md#161]
Hi, I am optimizing my program using JAX-MD's neighbor list module. When I need to calculate real space electrostatic interaction, I need to update the neighbor list.
```
def real_space(positions, Qlocal, box, kappa):

    # --- build neighborlist ---
    # It is un safe and tricky that I use a variable from outer function
    neighbor = nbr # .update(positions) # = neighbor_list_fn.allocate(positions)
```
When I use `nbr.update` in `real_space` and jit it, an error occurs at runtime:
```
Traceback (most recent call last):
  File "/share/home/jichen/work/ADMP/demo.py", line 1475, in <module>
    ereal, freal = jitted_pme_real_energy_and_force(positions, Qlocal, box, kappa)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/_src/api.py", line 411, in cache_miss
    out_flat = xla.xla_call(
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 1618, in bind
    return call_bind(self, fun, *args, **params)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 1609, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 1621, in process
    return trace.process_call(self, fun, tracers, params)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 615, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/interpreters/xla.py", line 622, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/linear_util.py", line 262, in memoized_fun
    ans = call(fun, *args)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/interpreters/xla.py", line 694, in _xla_callable
    return lower_xla_callable(fun, device, backend, name, donated_invars, *arg_specs).compile().unsafe_call
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/interpreters/xla.py", line 702, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1522, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1500, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/share/home/jichen/work/ADMP/demo.py", line 1320, in real_space
    neighbor = neighbor_list_fn.allocate(positions)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 767, in <lambda>
    neighbor_list_fn(R,
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 753, in neighbor_list_fn
    cell_list_fn = (cell_list(box_size, cell_size, R, capacity_multiplier) if
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 283, in cell_list
    cell_capacity = _estimate_cell_capacity(
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 180, in _estimate_cell_capacity
    return int(cell_capacity * buffer_size_multiplier)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 545, in __int__
    def __int__(self): return self.aval._int(self)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax/core.py", line 991, in error
    raise ConcretizationTypeError(arg, fname_context)
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(float64[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
While tracing the function real_space at /share/home/jichen/work/ADMP/demo.py:1316 for jit, this concrete value was not available in Python because it depends on the value of the argument 'positions'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share/home/jichen/work/ADMP/demo.py", line 1475, in <module>
    ereal, freal = jitted_pme_real_energy_and_force(positions, Qlocal, box, kappa)
  File "/share/home/jichen/work/ADMP/demo.py", line 1320, in real_space
    neighbor = neighbor_list_fn.allocate(positions)
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 767, in <lambda>
    neighbor_list_fn(R,
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 753, in neighbor_list_fn
    cell_list_fn = (cell_list(box_size, cell_size, R, capacity_multiplier) if
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 283, in cell_list
    cell_capacity = _estimate_cell_capacity(
  File "/share/home/jichen/.local/envs/admp/lib/python3.9/site-packages/jax_md/partition.py", line 180, in _estimate_cell_capacity
    return int(cell_capacity * buffer_size_multiplier)
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(float64[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or `jnp.array(x, int)` instead.
While tracing the function real_space at /share/home/jichen/work/ADMP/demo.py:1316 for jit, this concrete value was not available in Python because it depends on the value of the argument 'positions'.
```
I want to ask if neighbor.update can be used in the jit function, and what's going wrong with this code. I will provide more detailed info if you need. Thanks in advance! I appreciate you brilliant JAX-MD work, it helps me a lot!

**Comment by sschoenholz** [comment]
Hey! Thanks for reaching out. `new_nbrs = nbrs.update(positions)` can be called inside a jitted function. However, because of XLA's static shape requirements, the neighbor list might not be able to fit all of the neighbors. As such, one should usually check `new_nbrs.did_buffer_overflow` to make sure that nothing bad happened inside the jitted function. Thus usually the usage looks something like this,
```python
@jit
def update_fn(state, nbrs):
  state = step_fn(state, neighbor=nbrs)
  nbrs = nbrs.update(state.position)
  return state, nbrs

nbrs = neighbor_fn.allocate(state.position)
state, nbrs = update_fn(state, nbrs)
print(nbrs.did_buffer_overflow)
```

Looking at the error message you pasted, I notice that the failing line is 
```
  File "/share/home/jichen/work/ADMP/demo.py", line 1320, in real_space
    neighbor = neighbor_list_fn.allocate(positions)
```
so it seems like the problem is an allocation rather than an update. Is it possible you're accidentally calling `allocate`? 

If this doesn't help, would you mind posting a short reproducing code for your issue? I'd be happy to look into it!

**Comment by Roy-Kid** [comment]
Hi, I am sorry to take your time to answer my stupid question. I have fixed the bug and it blames me. By the way, If neighbor_fn and nbr.allocate/update not in a jitted function, they are also jitted when initializing the neighbor list. right?

**Comment by sschoenholz** [comment]
No worries at all, thanks for the question! At the moment, `neighbor_fn.allocate` and `neighbor_fn.update` are not end-to-end JIT (although some sub-functions are JIT). If you want to explicitly jit, I would recommend doing something like `update_fn = jit(neighbor_fn.update)` and then using that. Note, `allocate_fn = jit(neighbor_fn.allocate)` won't work since the interior of the allocate function uses dynamic shapes to allocate the size of the neighbor list.
