### ISSUE TITLE
Broadcasting error using parameter vectors on mapped functions

### ISSUE THREAD

**Issue by adrhill** [google/jax-md#190]
First of all, thank you for the amazing package!

I was wondering whether `smap`'ed functions such as potentials can use parameter vectors. The [`smap.pair` docs](https://jax-md.readthedocs.io/en/main/jax_md.smap.html#jax_md.smap.pair) say:
```
    kwargs: Arguments providing parameters to the mapped function. In cases
      where no species information is provided these should be either 

        1) a scalar 
        2) an ndarray of shape `[n]`
        3) an ndarray of shape `[n, n]`,
        4) a binary function that determines how per-particle parameters are to be combined
        5) a binary function as well as a default set of parameters as in 2)
```
I've tried using option 2) to apply a parameter vector to a potential, e.g. this wrapper around `energy.lennard_jones`:
```python
def my_lennard_jones(dr, p=[1, 1], **kwargs):
    return energy.lennard_jones(dr, sigma=p[0], epsilon=p[1], **kwargs)
```

Running an `N=3` body simulation with `smap.pair` and a parameter vector of size 2, I get the error
```
ValueError: Incompatible shapes for broadcasting: ((1, 2), (3, 3))
```

using  JAX `0.3.7` and JAX-MD `0.1.26` on Python `3.9.11`.

## MVE
Using the aforementioned wrapper around `energy.lennard_jones`:
```python
import jax.numpy as np
from jax import grad, random
from jax.config import config

config.update("jax_enable_x64", True)

from jax_md import energy, smap, space

f32 = np.float32
f64 = np.float64

key = random.PRNGKey(0)

def my_lennard_jones(dr, p=[1, 1], **kwargs):
    return energy.lennard_jones(dr, sigma=p[0], epsilon=p[1], **kwargs)

N = 3
dimension = 2
box_size = 5

key, split = random.split(key)
R = random.uniform(split, (N, dimension), minval=0.0, maxval=box_size, dtype=f64)
displacement, shift = space.periodic(box_size)

def test_pair(displacement_or_metric, species=None, p=[1, 1]):
    p = np.array(p, dtype=f32)

    return smap.pair(
        my_lennard_jones,
        space.canonicalize_displacement_or_metric(displacement_or_metric),
        species=species,
        p=p,
    )

energy_fn = test_pair(displacement, p=[1, 1])
print(energy_fn(R))
force = -grad(energy_fn)(R)
print(force)
```

Full traceback:
<details>

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 120, in broadcast_shapes
    return _broadcast_shapes_cached(*shapes)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/util.py", line 219, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/util.py", line 212, in cached
    return f(*args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 126, in _broadcast_shapes_cached
    return _broadcast_shapes_uncached(*shapes)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 142, in _broadcast_shapes_uncached
    raise ValueError("Incompatible shapes for broadcasting: {}"
ValueError: Incompatible shapes for broadcasting: ((1, 2), (3, 3))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/funks/Developer/jax-md-playground/experiments/debug.py", line 45, in <module>
    print(energy_fn(R))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax_md/smap.py", line 343, in fn_mapped
    return high_precision_sum(_diagonal_mask(fn(dr, **_kwargs)),
  File "/Users/funks/Developer/jax-md-playground/experiments/debug.py", line 18, in my_lennard_jones
    return energy.lennard_jones(dr, sigma=p[0], epsilon=p[1], **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax_md/energy.py", line 193, in lennard_jones
    idr = (sigma / dr)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 4538, in deferring_binary_op
    return binary_op(self, other)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/api.py", line 466, in cache_miss
    out_flat = xla.xla_call(
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/core.py", line 1771, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/core.py", line 1787, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/core.py", line 660, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/dispatch.py", line 149, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/linear_util.py", line 285, in memoized_fun
    ans = call(fun, *args)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/dispatch.py", line 197, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/dispatch.py", line 228, in lower_xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/profiler.py", line 206, in wrapper
    return func(*args, **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1844, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1816, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 239, in true_divide
    x1, x2 = _promote_args_inexact("true_divide", x1, x2)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 327, in _promote_args_inexact
    return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 227, in _promote_shapes
    result_rank = len(lax.broadcast_shapes(*shapes))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 122, in broadcast_shapes
    return _broadcast_shapes_uncached(*shapes)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 142, in _broadcast_shapes_uncached
    raise ValueError("Incompatible shapes for broadcasting: {}"
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Incompatible shapes for broadcasting: ((1, 2), (3, 3))

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/funks/Developer/jax-md-playground/experiments/debug.py", line 45, in <module>
    print(energy_fn(R))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax_md/smap.py", line 343, in fn_mapped
    return high_precision_sum(_diagonal_mask(fn(dr, **_kwargs)),
  File "/Users/funks/Developer/jax-md-playground/experiments/debug.py", line 18, in my_lennard_jones
    return energy.lennard_jones(dr, sigma=p[0], epsilon=p[1], **kwargs)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax_md/energy.py", line 193, in lennard_jones
    idr = (sigma / dr)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 4538, in deferring_binary_op
    return binary_op(self, other)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 239, in true_divide
    x1, x2 = _promote_args_inexact("true_divide", x1, x2)
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 327, in _promote_args_inexact
    return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))
  File "/Users/funks/Library/Caches/pypoetry/virtualenvs/jax-md-playground-UowHBS0s-py3.9/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 227, in _promote_shapes
    result_rank = len(lax.broadcast_shapes(*shapes))
ValueError: Incompatible shapes for broadcasting: ((1, 2), (3, 3))
```

</details>

**Comment by sschoenholz** [comment]
Thanks for trying out the library and for all of your great documentation contributions recently! Can you say a bit more about what you're trying to do? Typically, in option 2, `[n]` refers to the number of particles so I think the code above is working as expected (in the sense that what you wrote should not be legal) although I think the error message could be improved, so I'll try to get it to print out something more sensible. Essentially, under the hood, when you pass an array of parameters of shape `[n]` to an `smap.pair` function, it computes the parameters for an interaction between particles $(i, j)$ as $(p_i + p_j) / 2$ by default. This can be overridden by also passing a function along with the parameters (which would be case 5).

If the goal is to write a lennard-jones potential (or any energy function) so that the input is a parameter vector rather than specifying the different parameters separately (which I could see being useful for optimization) then would something like this work instead?
```
import jax.numpy as np
from jax import grad, random
from jax.config import config

config.update("jax_enable_x64", True)

from jax_md import energy, smap, space

f32 = np.float32
f64 = np.float64

key = random.PRNGKey(0)

N = 3
dimension = 2
box_size = 5

key, split = random.split(key)
R = random.uniform(split, (N, dimension), minval=0.0, maxval=box_size, dtype=f64)
displacement, shift = space.periodic(box_size)

def lennard_jones_parameters(displacement_or_metric, p):
  def energy_fn(R, **kwargs):
    _p = kwargs.get('p', p)
    lj_fn = energy.lennard_jones_pair(displacement_or_metric, 
                                      sigma=_p[0], 
                                      epsilon=_p[1])
    return lj_fn(R)
  return energy_fn

energy_fn = lennard_jones_parameters(displacement, np.array([1.0, 1.0]))
energy_fn(R)
```

If this is not your goal then let me know and I'm happy to iterate to figure out how to get this working!

**Comment by adrhill** [comment]
Thank you for the in-depth answer!

> Can you say a bit more about what you're trying to do? 

The wrapped Lennard-Jones potential was just a minimal example, I was actually trying to use a neural network (or any sort of parametrized universal function approximator) to approximate potentials. As you mentioned, passing a big array instead of thousands of individual scalar arguments would useful for optimization. 

> Typically, in option 2, [n] refers to the number of particles so I think the code above is working as expected 

I see, this is where my mistake was!

> would something like this work instead?

This does indeed work as long as there is only a single species. 
Using option 3 from the docs as an example, I think my issue boils down to the following: 
Using `n` bodies and `p` parameters for the potential, JAX-MD's `smap` supports passing `p` `[n, n]` matrices, whereas I was looking to pass an `[n, n]` matrix of `p`-dimensional arrays (basically one big `[n, n, p]` array).

**Comment by sschoenholz** [comment]
Thanks for clarifying! Just to make sure I understand, is the goal to pass a separate set of parameters for each interaction pair type? I think it would not be hard to get smap to work in this case, I'll try to submit something to enable it over the weekend.

**Comment by adrhill** [comment]
> is the goal to pass a separate set of parameters for each interaction pair type?

Yes exactly. That would be great! :)

**Comment by sschoenholz** [comment]
Hey! Sorry about the long lapse, I've been traveling and this ended up being a bit more involved than I had expected. I'm still not totally happy with the solution, but I checked in 8633cd5ce50ac13f3ebbcc99f4670cfcbed4841e which addresses this issue. Let me know how it works for you.

This change introduces the notion of a `ParameterTree` and a `ParameterTreeMapping`. A `ParameterTree` contains a PyTree containing any data you want to pass to the keyword argument (so it could be generated by a NN module) and a `ParameterTreeMapping` that determines how the parameters are passed to the function with analogy to how array-like parameters get passed into smapped functions. `ParameterTreeMapping` can be either `Global` (each particle gets the same set of parameters), `PerParticle` (each particle gets one set of parameters and each pair of particles get parameters that are determined by combining the per-particle values), `PerBond` (each pair of particles gets its own set of parameters, this is the case you asked for), `PerSpecies` (each pair of species gets its own set of parameters).

Here's how your example would look in the setup.
```python
import jax.numpy as np
from jax import grad, random
from jax.config import config

config.update("jax_enable_x64", True)

from jax_md import energy, smap, space

f32 = np.float32
f64 = np.float64

key = random.PRNGKey(0)

def my_lennard_jones(dr, p=[1, 1], **kwargs):
    return energy.lennard_jones(dr, sigma=p[0], epsilon=p[1], **kwargs)

N = 3
dimension = 2
box_size = 5

key, split = random.split(key)
R = random.uniform(split, (N, dimension), minval=0.0, maxval=box_size, dtype=f64)
displacement, shift = space.periodic(box_size)

def test_pair(displacement_or_metric, species=None, p=[1, 1]):
    p = smap.ParameterTree(np.array(p, dtype=f32), smap.ParameterTreeMapping.Global)

    return smap.pair(
        my_lennard_jones,
        space.canonicalize_displacement_or_metric(displacement_or_metric),
        species=species,
        p=p,
    )

energy_fn = test_pair(displacement, p=[1, 1])
print(energy_fn(R))
force = -grad(energy_fn)(R)
print(force)
```

**Comment by adrhill** [comment]
Awesome, I'll check it out right away. Thank you so much!

**Comment by abhijeetgangan** [comment]
Already resolved.
