### ISSUE TITLE
space.map_bond doesn't like kwargs

### ISSUE THREAD

**Issue by emilannevelink** [google/jax-md#204]
I'm trying to run an NPT simulation for which I need to pass kwargs to the energy_fn, but it seems like space.map_bond cannot vmap over the kwargs. Here is the error I get

```
Traceback (most recent call last):
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax/_src/api.py", line 1501, in _mapped_axis_size
    size, = mapped_axis_sizes
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/pressure/minimum_pressure.py", line 55, in <module>
    E.append(energy_fn(pos, nbrs, box=box))
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax_md/energy.py", line 1444, in energy_fn
    dr = space.map_bond(metric)(R[neighbor.idx[0]], R[neighbor.idx[1]],**kwargs) #might need to revise kwargs
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax/_src/api.py", line 1470, in vmap_f
    _mapped_axis_size(in_tree, args_flat, in_axes_flat, "vmap",
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax/_src/api.py", line 1514, in _mapped_axis_size
    assert treedef_is_leaf(leaf)
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/pressure/minimum_pressure.py", line 55, in <module>
    E.append(energy_fn(pos, nbrs, box=box))
  File "/ocean/projects/cts180021p/anneveli/.conda/envs/jaxMD/lib/python3.8/site-packages/jax_md/energy.py", line 1444, in energy_fn
    dr = space.map_bond(metric)(R[neighbor.idx[0]], R[neighbor.idx[1]],**kwargs) #might need to revise kwargs
AssertionError
```

The simulation I am trying to run uses the eam_neighbor_list potential and the periodic_general space. I think it may be something more general in the periodic_general space that is preventing map_bond from vectorizing over the inputs.

My solution was to use a `partial` operator to bake in the kwargs before the map_bond function.

```
metricp = partial(metric, **kwargs)
dr = space.map_bond(metricp)(R[neighbor.idx[0]], R[neighbor.idx[1]])#,**kwargs) #might need to revise kwargs
```

I tried to make a minimum working example, but the potential I'm using is in a format that the standard jaxmd couldn't read so I had to make some changes to `load_lammps_eam_parameters` 

I added the following lines to accept potentials with 6 columns

```
if len(re.split(' +',raw_text[6].strip()))>1:
    data = [maybe_downcast([float(i) for i in re.split(' +',rt.strip())]) for rt in raw_text[6:]]
    data = jnp.concatenate(data)
  else:
    data = maybe_downcast([float(i)  for i in raw_text[6:-1]])
```

Here is the minimum working example 
[minimum_pressure.py.zip](https://github.com/google/jax-md/files/9095403/minimum_pressure.py.zip)

and here is the potential
[2016--Nichol-A-Ackland-G-J--Li-eam.txt](https://github.com/google/jax-md/files/9095425/2016--Nichol-A-Ackland-G-J--Li-eam.txt)

**Comment by sschoenholz** [comment]
Thanks for raising this! Sorry for the delay in reply, I was traveling and lost track of issues. I think your analysis was spot on and the way we usually solve this is, exactly as you suggested, to partial evaluate the metric before sending into `map_bond`. e13f48fcf6a18a957ff7d8d46c5664f180cbfcf3 includes this fix for the EAM potentials. 

It would be possible to have the `map_bond`, `map_product`, and `map_neighbor` functions automatically not vmap over keyword arguments (essentially folding the partial evaluation into those functions). I haven't been inclined to do that up to this point because it wasn't clear that this behavior was always what one would want, but maybe it would be better. What do you think?

Finally, is that 6 column format common for EAM parameters? I added your fix to our EAM loader for convenience.

Let me know if you come across anything else or if you have any suggestions and thanks for the report!

**Comment by emilannevelink** [comment]
Thanks, Sam! This is great. 

For the keyword arguments, to me it doesn't make a difference whether it's a separate partial evaluation or wrapped into the functions. I don't know enough to say if there is a performance boost one way or the other. I may look a little cleaner if the partial evaluation would be wrapped into the map functions. I can't see a reason why it wouldn't be the expected behavior to have the kwargs of the metric function evaluated with the metric function. Is it possible that one of the kwargs changes over the vmap?
